### ISSUE TITLE
VS Crashing with PTVS

### ISSUE THREAD

**Issue by modulexcite** [madskristensen/ExtensibilityTools#34]
### Installed product versions
- OS: Windows 7 64-bit
- Python version: 3.5.1 
- Visual Studio: 2015 Professional
- This extension: 1.8.42

### Description
visual studio crashes when working with python files, I've to disable this extension to be able to work with python files. please see below for the exception log.
Otherwise love the extension and thanks for the great work.

### Steps to recreate
1. Open a python code file.

### Current behavior
It's crashing visual studio upon opening a python file.

### Expected behavior
I should be able to work with python files without having to disable this extension.

### Exception Log
Time: 2016-05-08T19:54:55
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
   at System.Text.Encoding.GetDataItem()
   at System.Text.Encoding.get_HeaderName()
   at MadsKristensen.ExtensibilityTools.EditorMargin.BottomMargin+<>c__DisplayClass12_0.<UpdateEncodingLabel>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by modulexcite** [comment]
Thanks for fixing it, you rock!






On Tue, May 17, 2016 at 3:42 PM -0700, "Mads Kristensen" <notifications@github.com> wrote:












Closed #34 via e58f21f.
