### ISSUE TITLE
NullReferenceException while Debugging

### ISSUE THREAD

**Issue by SamuelEnglard** [madskristensen/ExtensibilityTools#56]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.10.196

### Description
```
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregator.GetClassificationSpans(Microsoft.VisualStudio.Text.SnapshotSpan)
   at MadsKristensen.ExtensibilityTools.EditorMargin.BottomMargin.<UpdateClassificationLabel>b__15_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

### Steps to recreate
Debugging large C# solution

### Current behavior
Crashing Visual Studio

### Expected behavior
Not crashing Visual Studio

**Comment by ReDucTor** [comment]
I'm getting the same issue in VS 2015, I needed to uninstall the extension it was happening that often.

**Comment by madskristensen** [comment]
Fixed in latest commits

**Comment by SylwesterZarebski** [comment]
Is this 'latest commits' available on marketplace? I have the same (i suppose) exception on latest version (1.10.198):
```
2018-01-31 11:41:03: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregator.GetClassificationSpans(SnapshotSpan span)
   at MadsKristensen.ExtensibilityTools.EditorMargin.BottomMargin.<UpdateClassificationLabel>b__15_0() in C:\projects\extensibilitytools\src\EditorMargin\BottomMargin.cs:line 134
```
